/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BiomarkerRouteImport } from './routes/biomarker'
import { Route as IndexRouteImport } from './routes/index'

const BiomarkerRoute = BiomarkerRouteImport.update({
  id: '/biomarker',
  path: '/biomarker',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biomarker': typeof BiomarkerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biomarker': typeof BiomarkerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biomarker': typeof BiomarkerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/biomarker'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/biomarker'
  id: '__root__' | '/' | '/biomarker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BiomarkerRoute: typeof BiomarkerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/biomarker': {
      id: '/biomarker'
      path: '/biomarker'
      fullPath: '/biomarker'
      preLoaderRoute: typeof BiomarkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BiomarkerRoute: BiomarkerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
